🚸 A few more Vagrant features for ease of use.
robertdebock/ansible-modules-workshop pull request #1
Opened 2018-10-12 20:40 UTC by bbaassssiiee

Rather than using VirtualBox with manual setup, just install Ansible and Vagrant and run 'vagrant up'.

2018-10-15 18:06 UTC, robertdebock commented on Vagrantfile
> +  config.vbguest.auto_update = false
Thanks @bbaassssiiee.

I'm seeing (On Linux) this error when running `vagrant up`:
```
An error occurred while executing the action on the 'controlnode'
machine. Please handle this error then try again:

There are errors in the configuration of this machine. Please fix
the following errors and try again:

Vagrant:
* Unknown configuration section 'vbguest'.
```

2018-10-15 18:06 UTC, robertdebock commented on Vagrantfile
> +  config.hostmanager.enabled = true
I'm not 100% sure what the hostmanager does, but I assume it sets a hostname and fills /etc/hosts. The (included) role robertdebock.common does that too.

2018-10-15 18:07 UTC, robertdebock requested changes
All in all the proposed changes do not work for me, but I've learned a bit, thanks @bbaassssiiee .

2018-10-15 18:07 UTC, robertdebock commented on Vagrantfile
> +    ansible.galaxy_role_file = "roles/requirements.yml"
The modules listed in there are installed in the playbook:
```
    - name: install required pip modules
      pip:
        name: "{{ item }}"
        state: present
      with_items:
        - pycodestyle
        - mock
        - voluptuous
```

2018-11-14 12:07 UTC, bbaassssiiee commented
Closing due to lack of activity.

2018-11-14 12:07 UTC, closed without merging